#= require jquery
#= require jquery_ujs
#= require rails-ujs
#= require turbolinks
#= require bootstrap/button
# = require simditor/module
# = require simditor/hotkeys
# = require simditor/uploader
#= require moment
#= require moment_with_locales
#= require bootstrap-datetimepicker
#= require_tree .
